// <auto-generated />
namespace Hacking_INF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Log_Anonymous_Submissions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Log_Anonymous_Submissions));
        
        string IMigrationMetadata.Id
        {
            get { return "201612091324482_Log_Anonymous_Submissions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
